/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.clothingstore.gui.components.invoicesHistory;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.BorderFactory;

/**
 *
 * @author yanti
 */
public class Invoice extends javax.swing.JPanel {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        Detail = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        Price = new javax.swing.JLabel();
        IdInvoice = new javax.swing.JLabel();
        EmployeeInfo = new javax.swing.JPanel();
        EmployeeName = new javax.swing.JLabel();
        Time = new javax.swing.JPanel();
        Date = new javax.swing.JLabel();
        TimeHour = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());
        setPreferredSize(new Dimension(40, 60));
        setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/config/icon/search.png"))); // NOI18N
        add(Icon, java.awt.BorderLayout.LINE_START);

        Detail.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        Detail.setLayout(new java.awt.BorderLayout());

        Panel.setLayout(new java.awt.GridLayout(2, 0));

        Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Price.setText("4.000.000 Đ");
        Panel.add(Price);

        IdInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdInvoice.setText("64747374");
        Panel.add(IdInvoice);

        Detail.add(Panel, java.awt.BorderLayout.LINE_START);

        EmployeeInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 12, 5, 5));
        EmployeeInfo.setLayout(new java.awt.GridLayout(2, 0));

        EmployeeName.setText("Bành Văn A");
        EmployeeInfo.add(EmployeeName);

        Detail.add(EmployeeInfo, java.awt.BorderLayout.CENTER);

        add(Detail, java.awt.BorderLayout.CENTER);

        Time.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Time.setLayout(new java.awt.GridLayout(2, 1));

        Date.setText("05/10/2022");
        Time.add(Date);

        TimeHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeHour.setText("16h30");
        Time.add(TimeHour);

        add(Time, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JPanel Detail;
    private javax.swing.JPanel EmployeeInfo;
    private javax.swing.JLabel EmployeeName;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel IdInvoice;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Price;
    private javax.swing.JPanel Time;
    private javax.swing.JLabel TimeHour;
    // End of variables declaration//GEN-END:variables
}
