/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.clothingstore.gui.components;

/**
 *
 * @author yanti
 */
public class Control extends javax.swing.JPanel {

    /**
     * Creates new form Control
     */
    public Control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IncreButton = new javax.swing.JButton();
        ReduceButton = new javax.swing.JButton();
        Value = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        IncreButton.setText("+");
        add(IncreButton, java.awt.BorderLayout.LINE_END);

        ReduceButton.setText("-");
        ReduceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReduceButtonActionPerformed(evt);
            }
        });
        add(ReduceButton, java.awt.BorderLayout.LINE_START);

        Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Value.setText("jLabel1");
        add(Value, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ReduceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReduceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReduceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IncreButton;
    private javax.swing.JButton ReduceButton;
    private javax.swing.JLabel Value;
    // End of variables declaration//GEN-END:variables
}
