/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.clothingstore.gui.components;

import java.awt.*;

import javax.swing.ImageIcon;

import com.itextpdf.text.Image;

/**
 *
 * @author yanti
 */
public class Product extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Image = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setPreferredSize(new java.awt.Dimension(199, 280));
        setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setLayout(new java.awt.GridBagLayout());

        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/config/image/polo3.png"));
        java.awt.Image originalImage = originalIcon.getImage();
        java.awt.Image scaledImage = originalImage.getScaledInstance(180, 180, java.awt.Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        Image.setIcon(scaledIcon); // NOI18N
        Image.setPreferredSize(new java.awt.Dimension(180, 178));
        Header.add(Image, new java.awt.GridBagConstraints());

        add(Header, java.awt.BorderLayout.CENTER);

        Footer.setBackground(new java.awt.Color(255, 255, 255));
        Footer.setPreferredSize(new java.awt.Dimension(193, 65));
        Footer.setLayout(new java.awt.GridLayout(2, 1));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Black Polo");
        Footer.add(Name);

        Price.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        Price.setForeground(new java.awt.Color(240, 18, 18));
        Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Price.setText("350.000");
        Footer.add(Price);

        add(Footer, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    // End of variables declaration//GEN-END:variables
}
