/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.clothingstore.gui.customer;

import java.awt.Color;

import javax.swing.text.AbstractDocument.Content;

/**
 *
 * @author yanti
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setBackground(new Color(0xAACDEF));

        Search = new javax.swing.JPanel();
        Value = new javax.swing.JTextField();
        Button = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(340, 70));
        setLayout(new java.awt.BorderLayout());

        Search.setPreferredSize(new java.awt.Dimension(355, 50));      
        Search.setBackground(new Color(0xAACDEF));
        Search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Value.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Value.setToolTipText("");
        Value.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        Search.add(Value, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 280, 30));
        Search.add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 40, 30));

        add(Search, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JPanel Search;
    private javax.swing.JTextField Value;
    // End of variables declaration//GEN-END:variables
}
