/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.clothingstore.gui.customer;

/**
 *
 * @author yanti
 */
public class Invoice extends javax.swing.JPanel {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Index = new javax.swing.JLabel();
        None = new javax.swing.JLabel();
        NameShop = new javax.swing.JTextField();
        Content = new javax.swing.JPanel();
        Scroll = new javax.swing.JScrollPane();
        Invoices = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        TextSum = new javax.swing.JLabel();
        Value = new javax.swing.JLabel();
        ButtonCancel = new javax.swing.JButton();
        ButtonPay = new javax.swing.JButton();
        ButtonPrint = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(245, 370));
        setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 131, 205));
        Header.setLayout(new java.awt.BorderLayout());

        Index.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Index.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Index.setText("45");
        Index.setPreferredSize(new java.awt.Dimension(30, 45));
        Header.add(Index, java.awt.BorderLayout.LINE_START);

        None.setPreferredSize(new java.awt.Dimension(30, 45));
        Header.add(None, java.awt.BorderLayout.LINE_END);

        NameShop.setEditable(false);
        NameShop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NameShop.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameShop.setText("The Shop VIP");
        Header.add(NameShop, java.awt.BorderLayout.CENTER);

        add(Header, java.awt.BorderLayout.PAGE_START);

        Content.setLayout(new java.awt.BorderLayout());

        Invoices.setBackground(new java.awt.Color(255, 255, 255));
        Invoices.setLayout(new java.awt.GridLayout(1, 0));
        Scroll.setViewportView(Invoices);

        Content.add(Scroll, java.awt.BorderLayout.CENTER);

        add(Content, java.awt.BorderLayout.CENTER);

        Footer.setPreferredSize(new java.awt.Dimension(301, 120));
        Footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextSum.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TextSum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextSum.setText("Tổng Thanh Toán");
        Footer.add(TextSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 30));

        Value.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Value.setForeground(new java.awt.Color(255, 51, 51));
        Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Value.setText("3.000.000");
        Footer.add(Value, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 30));

        ButtonCancel.setText("Hủy");
        ButtonCancel.setPreferredSize(new java.awt.Dimension(72, 20));
        Footer.add(ButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        ButtonPay.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ButtonPay.setText("Thanh Toán");
        ButtonPay.setPreferredSize(new java.awt.Dimension(72, 20));
        Footer.add(ButtonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, 30));

        ButtonPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/config/icon/printer.png"))); // NOI18N
        Footer.add(ButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        add(Footer, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonPay;
    private javax.swing.JLabel ButtonPrint;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Index;
    private javax.swing.JPanel Invoices;
    private javax.swing.JTextField NameShop;
    private javax.swing.JLabel None;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JLabel TextSum;
    private javax.swing.JLabel Value;
    // End of variables declaration//GEN-END:variables
}
