/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.clothingstore.gui.admin.Dashboard;

/**
 *
 * @author yanti
 */
public class Card extends javax.swing.JPanel {

    /**
     * Creates new form Card
     */
    public Card() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        NamePanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Value = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/config/icon/coin.png"))); // NOI18N
        add(Icon, java.awt.BorderLayout.PAGE_START);

        MainPanel.setLayout(new java.awt.GridLayout(3, 0));

        NamePanel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NamePanel.setText("New Invoice");
        MainPanel.add(NamePanel);

        jPanel2.setLayout(new java.awt.BorderLayout());
        MainPanel.add(jPanel2);

        Value.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Value.setText("300.000");
        MainPanel.add(Value);

        add(MainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NamePanel;
    private javax.swing.JLabel Value;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
